on: [push]
jobs:
  job_1:
    name: Build and deploy Segment Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Preparing Function
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build and deploy Segment Function
        uses: christyharagan/sloth-github-action@v1.2.0
        with:
          segment-access-token: ${{ secrets.SEGMENT_ACCESS_TOKEN }}
          segment-workspace-slug: ${{ secrets.SEGMENT_WORKSPACE_SLUG }}
          segment-workspace-id: ${{ secrets.SEGMENT_WORKSPACE_ID }}
